#@ load("@ytt:data", "data")
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: ray-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: raycluster-kuberay-head-svc
          port: 8265
  virtualhost:
    fqdn: #@ 'ray.' + data.values.fqdn_domain