#@data/values
---
ray_image_tag: REPLACE_RAY_IMAGE_TAG
ray_operator_image_tag: REPLACE_OPERATOR_IMAGE_TAG
ray_apiserver_image_tag: REPLACE_APISERVER_IMAGE_TAG
ray_cluster_head_resources_limits_memory: REPLACE_CLUSTER_HEAD_RESOURCES_LIMITS_MEMORY
ray_cluster_head_resources_requests_memory: REPLACE_CLUSTER_HEAD_RESOURCES_REQUESTS_MEMORY
ray_cluster_worker_common_resources_limits_memory: REPLACE_CLUSTER_WORKER_COMMON_RESOURCES_LIMITS_MEMORY
ray_cluster_worker_common_resources_requests_memory: REPLACE_CLUSTER_WORKER_COMMON_RESOURCES_REQUESTS_MEMORY
ray_operator_service_type: REPLACE_OPERATOR_SERVICE_TYPE
ray_api_server_service_type: REPLACE_API_SERVER_SERVICE_TYPE
